**Importação das Biblioteca**


In [29]:
import pandas as pd
import numpy as np

Criação de um Array a partir de uma lista:

In [21]:
lista1=[1,2,3,4,5,6]
array1=np.array(lista1)
print(array1)

[1 2 3 4 5 6]


Principais Funções:

In [7]:
print(array1.dtype)

int64


In [22]:
print(array1.shape)

(6,)


In [11]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
number_one=np.ones((2,3))
print(number_one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
vazio=np.empty((4,4))
print(vazio)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.11261162e-306]
 [9.34598925e-307 1.42419802e-306 8.01092457e-307 6.23053614e-307]
 [1.86919649e-306 1.78020848e-306 1.11258175e-306 1.78019082e-306]
 [1.33511290e-306 4.67296747e-307 7.23188049e-308 4.78406574e+199]]


In [17]:
sequencia=np.arange(99,999,100)
print(sequencia)

[ 99 199 299 399 499 599 699 799 899]


In [20]:
aleatorio=np.random.rand(2,3)
print(aleatorio)

[[0.69416368 0.79029244 0.23178681]
 [0.80987075 0.00574563 0.42994269]]


Funções para Manipulação de arrays Existente:

In [24]:
array2=array1.reshape((2,3))
print(array2)

[[1 2 3]
 [4 5 6]]


In [26]:
quebra=np.split(array2,2)
print(quebra)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [27]:
array3=np.array([1,2])
array4=np.array([3,4])
print(array3,array4)
uniao=np.concatenate([array3,array4])
print(uniao)

[1 2] [3 4]
[1 2 3 4]


**Operações com Séries Pandas**

Criação:

In [30]:
serie1=pd.Series([10,20,30],index=['a','b','c'])
print(serie1)

a    10
b    20
c    30
dtype: int64


Seleção por Índice:

In [33]:
print(serie1[['a']])
print(serie1[['a','c']])

a    10
dtype: int64
a    10
c    30
dtype: int64


Operações de Filtragem e Aritmétrica

In [34]:
filtro1=serie1[serie1>15]
print(filtro1)

b    20
c    30
dtype: int64


In [35]:
serie3=pd.Series([1,2,3,4,])
serie4=pd.Series([5,6,7,8])

#Operações Fundamentais:
print(serie3+serie4)
print('------')
print(serie3-serie4)
print('------')
print(serie3*serie4)
print('------')
print(serie3/serie4)
print('------')


0     6
1     8
2    10
3    12
dtype: int64
------
0   -4
1   -4
2   -4
3   -4
dtype: int64
------
0     5
1    12
2    21
3    32
dtype: int64
------
0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64
------


In [37]:
#Suporte e Valores Nulos:

serievazia=pd.Series([10,np.nan,30]) #NaN ='Null as Number'
print(serievazia)
print(serie3+serievazia)
print('-----------')
print(serie3-serievazia)
print('-----------')
print(serie3*serievazia)
print('-----------')
print(serie3/serievazia)

0    10.0
1     NaN
2    30.0
dtype: float64
0    11.0
1     NaN
2    33.0
3     NaN
dtype: float64
-----------
0    -9.0
1     NaN
2   -27.0
3     NaN
dtype: float64
-----------
0    10.0
1     NaN
2    90.0
3     NaN
dtype: float64
-----------
0    0.1
1    NaN
2    0.1
3    NaN
dtype: float64
